version: "3.9"

services:
  admin: 
    image: hariot/admin:latest
    build: 
      context: admin
      args:
        version: latest-SNAPSHOT
    env_file:
      - aliyun-access.env
      - aliyun-device.env
      - hariot-admin.env
      - hariot-database.env
    environment:
      HARIOT_DATABASE_HOST: db
    ports:
      - 8080:8080
    networks:
      - hariot-switch
    depends_on:
      - db

  db:
    image: hariot/db:latest
    build:
      context: db
    env_file:
      - hariot-database.env
    ports:
      - 3306:3306
    networks:
      - hariot-switch
          
  slave:
    image: hariot/slave:latest
    build:
      context: slave
    env_file:
      - aliyun-device.env
    

networks:
  hariot-switch:
    
    
       
